/**
 * Supabase REST Client
 * Thin wrapper around the PostgREST API — no npm package needed.
 *
 * Required env vars:
 *   VITE_SUPABASE_URL      e.g. https://xxxx.supabase.co
 *   VITE_SUPABASE_ANON_KEY  your project's anon/public key
 *
 * Supabase table schema (run once in the Supabase SQL editor):
 *
 *   CREATE TABLE visits (
 *     id          bigint generated by default as identity primary key,
 *     created_at  timestamptz default now(),
 *     country     text,
 *     country_code text,
 *     region      text,
 *     city        text,
 *     postal_code text,
 *     isp         text,
 *     timezone    text,
 *     referrer    text,
 *     page        text,
 *     user_agent  text,
 *     language    text,
 *     screen_width  int,
 *     screen_height int,
 *     session_id  text
 *   );
 *
 *   ALTER TABLE visits ENABLE ROW LEVEL SECURITY;
 *   CREATE POLICY "allow insert" ON visits FOR INSERT WITH CHECK (true);
 *   CREATE POLICY "allow select" ON visits FOR SELECT USING (true);
 */

const SUPABASE_URL     = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

function baseHeaders(extra = {}) {
  return {
    'Content-Type': 'application/json',
    'apikey': SUPABASE_ANON_KEY,
    'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
    ...extra,
  };
}

export const supabaseClient = {
  /** Returns true only when both env vars are present */
  isConfigured() {
    return !!(SUPABASE_URL && SUPABASE_ANON_KEY);
  },

  /**
   * Insert a single visit row.
   * @param {Object} row - Matches the visits table columns.
   * @returns {Promise<boolean>} true on success
   */
  async insertVisit(row) {
    if (!this.isConfigured()) {
      console.warn('⚠️  Supabase not configured — visit not persisted.');
      return false;
    }
    try {
      const res = await fetch(`${SUPABASE_URL}/rest/v1/visits`, {
        method: 'POST',
        headers: baseHeaders({ 'Prefer': 'return=minimal' }),
        body: JSON.stringify(row),
      });
      if (!res.ok) {
        const body = await res.text();
        console.warn('Supabase insert error:', res.status, body);
      }
      return res.ok;
    } catch (err) {
      console.warn('Supabase insert failed:', err.message);
      return false;
    }
  },

  /**
   * Fetch visits for the dashboard, most recent first.
   * @param {{ limit?: number, offset?: number }} opts
   * @returns {Promise<Object[]|null>}
   */
  async getVisits({ limit = 500, offset = 0 } = {}) {
    if (!this.isConfigured()) return null;
    try {
      const res = await fetch(
        `${SUPABASE_URL}/rest/v1/visits?select=*&order=created_at.desc&limit=${limit}&offset=${offset}`,
        { headers: baseHeaders() }
      );
      return res.ok ? res.json() : null;
    } catch (err) {
      console.warn('Supabase fetch failed:', err.message);
      return null;
    }
  },

  /**
   * Returns the total visit count via the PostgREST range header.
   * @returns {Promise<number|null>}
   */
  async getTotalCount() {
    if (!this.isConfigured()) return null;
    try {
      const res = await fetch(`${SUPABASE_URL}/rest/v1/visits?select=id&limit=1`, {
        headers: baseHeaders({ 'Prefer': 'count=exact', 'Range-Unit': 'items', 'Range': '0-0' }),
      });
      const cr = res.headers.get('content-range'); // e.g. "0-0/1234"
      return cr ? parseInt(cr.split('/')[1], 10) : null;
    } catch (err) {
      console.warn('Supabase count failed:', err.message);
      return null;
    }
  },

  // ── Events ───────────────────────────────────────────────────────────────

  /**
   * Insert a single event row.
   * @param {Object} row - Matches the events table columns.
   */
  async insertEvent(row) {
    if (!this.isConfigured()) return false;
    try {
      const res = await fetch(`${SUPABASE_URL}/rest/v1/events`, {
        method: 'POST',
        headers: baseHeaders({ 'Prefer': 'return=minimal' }),
        body: JSON.stringify(row),
      });
      if (!res.ok) console.warn('Supabase event insert error:', res.status, await res.text());
      return res.ok;
    } catch (err) {
      console.warn('Supabase insertEvent failed:', err.message);
      return false;
    }
  },

  /**
   * Fetch events for the dashboard, most recent first.
   * @param {{ limit?: number, offset?: number }} opts
   * @returns {Promise<Object[]|null>}
   */
  async getEvents({ limit = 300, offset = 0 } = {}) {
    if (!this.isConfigured()) return null;
    try {
      const res = await fetch(
        `${SUPABASE_URL}/rest/v1/events?select=*&order=created_at.desc&limit=${limit}&offset=${offset}`,
        { headers: baseHeaders() }
      );
      return res.ok ? res.json() : null;
    } catch (err) {
      console.warn('Supabase getEvents failed:', err.message);
      return null;
    }
  },

  /**
   * Total event count.
   * @returns {Promise<number|null>}
   */
  async getEventTotalCount() {
    if (!this.isConfigured()) return null;
    try {
      const res = await fetch(`${SUPABASE_URL}/rest/v1/events?select=id&limit=1`, {
        headers: baseHeaders({ 'Prefer': 'count=exact', 'Range-Unit': 'items', 'Range': '0-0' }),
      });
      const cr = res.headers.get('content-range');
      return cr ? parseInt(cr.split('/')[1], 10) : null;
    } catch (err) {
      console.warn('Supabase event count failed:', err.message);
      return null;
    }
  },
};

export default supabaseClient;
